#+title: A Lean Design Thinking Methodology (LDTM) for Machine Learning and  Modern Data Projects - Paper Summary
#+AUTHOR: DINH DUY KHA - 2019712308
#+DATE:
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}

In this paper, the authors propose *Lean Design Thinking Methodology* (LDTM), a software development methodology that combines the strength of CRISP-DM with Design Thinking and Lean Startup methodologies. LDTM helps speed up the development process while also encure that the solution meet the requirements by engaging with the customer frequently.

As an overview, LDTM works by combining three development methodologies: *Design Thinking*, *Lean Startup* and *CRISP-DM*.  The Design thinking principle is that the customer must be understood first before building the solution. In LDTM,  the "Empathize", "Define" and "Ideate" phases of Design Thinking is utilized. Lean Startup is a proposed methodology for running a start-up, which states that the minimum set of feature that satisfy early users should be developed first. Finally, CRISP-DM is an open standard that contains a complete blueprint for data mining projects containing six phases.

The resulting methodology is divided into three stages: *Business, Data and Product*, which is further divided into seven steps. The Bussiness stage is where the developers identify problems and propose the solutions. In Data stage, understanding and preparation of data is performed. Finally, in the Product stage, the solution is iterated through many version with the feedback of the customers.
The seven steps of LDTM are:
1. *Work Discovery*: The developers research about their customers and the requirements, then define the problem, objective and requirements for the project.
2. *Analytical Approach*: The developer identify the appropriate method that satisfy the requirements identified in the previous step.
3. *Data Resources*: The developers collect resources and data relavant to the target problem.
4. *Data Preparation*: Data is preprocessed into the final dataset used in the product.
5. *Build MVP*: The *Minimum Viable Product* (MVP) is built so that it could be quickly tested by users.
6. *Measure Value*: The developers then collect feedbacks from users so that the solution value is measured accurately.
7. *Learn & Update*: Finally, the developers update the product accordingly from users' feedbacks.



One weakness of proposed methodology is that it does not cover when to stop the development process. Engaging with the customer could be one solution to the problem. Another weakness of this paper is that there is no evaluation of LDTM, which makes its validity questionable.
