:PROPERTIES:
:ID:       01f66afd-111b-432f-99c0-51f593d36e5b
:END:
#+title: Cryptography

* Kerckhoffs' Principle
+ *Kerckhoffs' principle*: in any cryptography algorithm, only the key need to be kept secret. The crypto algorithm is not secret.
  + Secret algorithms is insecure.

* Perfect Secrecy
+ Perfect Secrecy (Shannon 1949): given a ciphertext c, an attacker cannot determine the message that was the plaintext. That is,
  $PR[E(k,m_{0}) = c] = PR[E(k,m_{1}) = c]$
+ To achieve perfect secrecy, the key length need to be greateer of equal than the message length (e.g., One Time Pad).
+ In practice, this is hard to achieve, so most encryption schemes only limit the computational power of the adversary
** Non-perfect secrecy
+ Non-perfect secrecy: Given two ciphertext $c_{1} = k xor m_{1}$ and $c_{2} = k xor m_{2}$
  Attacker can compute  $c_{1} xor c_{2} = m_{1} xor m_{2}$. Therefore, if $m_{1}$ is leak, $m_{2}$ is also leaked.



* Confusion vs. diffusion
+ *Confusion* obscure the relationship between plaintext and ciphertext (e.g., OTP)
+ *Diffusion* spread plaintext statistic through the ciphertext. For example, if we arrange the plaintext into a matrix and scramble the row and columns, we get a new ciphertext. The key for this kind of encryption is the matrix permutation.


* [[id:1db3d4da-1f08-4863-a8d0-2fd7cd5b962e][Attack Models of Cryptography]]
* [[id:a5b0504e-6bd1-41ff-aaec-dce6e7464b7a][Symmetric Key Encryption]]
